### ISSUE TITLE
Audit Team - Projects Review (02/05/2021 - 08/05/2020)

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Management#161]
- [x] Final Discussion: [TNBC Games](https://github.com/thenewboston-developers/Projects/issues/179)

- [x] Review: [TNBC JS SDK](https://github.com/thenewboston-developers/Projects/issues/176)

- [x] Review: [Kotlin Multiplaform Mobile SDK](https://github.com/thenewboston-developers/Projects/issues/169)

- [x] Review: [TNBAnon](https://github.com/thenewboston-developers/Projects/issues/201)

- [x] Review and Payout for [TNBcrow Mileston - 1](https://github.com/thenewboston-developers/Projects/issues/200)

- [x] Review: [tnbeverything](https://github.com/thenewboston-developers/Projects/issues/167)
