### ISSUE TITLE
Audit Team - Projects (09/05/2021 - 15/05/2020)

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Management#200]
- [x] [Example Online store using Keysign](https://github.com/thenewboston-developers/Projects/issues/168)

- [x] [TNB List](https://github.com/thenewboston-developers/Projects/issues/170)

- [x] [TNBPay](https://github.com/thenewboston-developers/Projects/issues/172)

- [x] [Digital Art buying and selling APP](https://github.com/thenewboston-developers/Projects/issues/177)

- [x] [Get It Now](https://github.com/thenewboston-developers/Projects/issues/182)

- [x] [Informative articles for thenewboston community](https://github.com/thenewboston-developers/Projects/issues/183)

- [x] [TNB Minecraft Integration](https://github.com/thenewboston-developers/Projects/issues/206)

- [x] [Blockchain Explorer - Milestone 1](https://github.com/thenewboston-developers/Projects/issues/205)

- [x] [Restaurants Self-Order - Milestone - 1](https://github.com/thenewboston-developers/Projects/issues/199)

**Comment by manishram** [comment]
Done
