### ISSUE TITLE
Audit Team - Projects (23/05/2021 - 29/05/2020)

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Management#213]
- [x] [Ideation: Offline-Centered TheNewBoston](https://github.com/thenewboston-developers/Projects/issues/184)

- [x] [tnBabel](https://github.com/thenewboston-developers/Projects/issues/185)

- [x] [TNBC Treasure Hunt](https://github.com/thenewboston-developers/Projects/issues/190)

- [x] [Machine Learning on TNB for Healthcare](https://github.com/thenewboston-developers/Projects/issues/194)

- [x] [Hierarchical deterministic (HD) Wallets for TNB](https://github.com/thenewboston-developers/Projects/issues/198)

**Comment by manishram** [comment]
Done
